spring:
  application:
    name: cachedemo
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health, env

infinispan:
  embedded:
    enabled: true
    config-xml: tasksCacheEmbedded.xml
  remote:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: prod
infinispan:
  embedded:
    enabled: false
  remote:
    enabled: true
    statistics: true
    client-intelligence: BASIC
    server-list: cachedemo-infinispan:11222
    use-auth: false
